version: '3.1'

services:
  # web:
  #   image: nginx
  #   ports:
  #   - 8000:80
  #   volumes:
  #   - wordpress:/var/www/html
  #   - /home/pi/wordpress/nginx.conf:/etc/nginx/nginx.conf


  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./volumes/nginx/html:/usr/share/nginx/html,readonly
      - ./volumes/nginx/conf/nginx.conf:/etc/nginx/nginx.conf,readonly


      
  php:
    image: wordpress:5.4.2-php7.2-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: myverysecurepassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - wordpress:/var/www/html
    - /home/pi/wordpress/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-kraken.conf

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: myverysecurepassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
    - db:/var/lib/mysql

volumes:
  wordpress:
  db: